import { IProduct } from './GeneralTypes';

export const mockProductsData: IProduct[] = [
  {
    id: 1,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 2,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
  {
    id: 3,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 4,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
  {
    id: 5,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 6,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
  {
    id: 7,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 8,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
  {
    id: 9,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 10,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
  {
    id: 11,
    title: 'Product 1',
    description: 'Description 1',
    price: 10,
    discountPercentage: 5,
    rating: 4,
    stock: 20,
    brand: 'Brand 1',
    category: 'Category 1',
    thumbnail: 'path/to/image1',
    images: ['path/to/image1_1', 'path/to/image1_2'],
  },
  {
    id: 12,
    title: 'Product 2',
    description: 'Description 2',
    price: 15,
    discountPercentage: 10,
    rating: 4.5,
    stock: 15,
    brand: 'Brand 2',
    category: 'Category 2',
    thumbnail: 'path/to/image2',
    images: ['path/to/image2_1', 'path/to/image2_2'],
  },
];
